export default function feuerwehrleistungswettkaempfe() {
    return (<>
        <h1>Feuerwehr-Leistungswettkaempfe</h1>
        <p>Seit mittlerweile &#252;ber 50 Jahren nimmt die Freiwillige Feuerwehr Rennertehausen an den j&#228;hrlich stattfindnenden Feuerwehr-Kreisleistungswettk&#228;mpfen in Korbach teil. Dies ist vorallem ein Verdienst des ehemaligen Ortsbrandmeisters und Gemeindebrandinspektor Erich Clemens, dem es immer gelang eine Wettkampfmanschaft zusammenzustellen. So besteht die Wettkampfmannschaft neben "Alten Hasen" auch zunehmend aus jungen Kameraden.</p>
        <p>Bei den Leistungswettkämpfen nehmen jährlich ca. 70 Feuerwehren auf Kreisebenen teil. Hier belegte die Feuerwehr Rennertehausen in den Jahren von 1975 - 1980 immer einen der vorderen Plätze und qualifizierte sich teilweise sogar für die Bezirks– und Hessenmeisterschaften. Durch die Reformierung der Wettkämpfe, die Verjüngung der Rennertehäuser Wettkampfmannschaft und eine immer größer werdende Leistungsdichte der andere Mannschaften fiel man zunächst auf mittlere Plätze ab. Erst in den letzten Jahren gelang der Rennertehäuser Wehr wieder der Anschluss an die Spitzenmannschaften und konnte sich zum Teil für die Bezirks– und Hessenmeisterschaft qualifizieren. Oft fuhr man jedoch enttäuscht von der Kreismeisterschaft, da die Qualifikation für die Bezirksmeisterschaft nur um wenige Plätze verfehlt wurde.</p>
        <p>1976 die Feuerwehr Rennertehausen bei den Leistungswettkämpfen in Korbach mit 1188 Punkten den 3. Platz und erlangte somit die Qualifikation für den Bezirksentscheid in Bad Hersfeld. Hierzu mußte das LF8 der Feuerwehr Allendorf ausgeliehen werden, da das neue LF8 für die Rennertehäuser Wehr erst im November 1976 ausgeliefert wurde. Während die Mannschaft mit dem Bus nach Bad Hersfeld anreiste führte Herrmann Clemens das LF8 der Allendörfer Wehr nach und blieb kurz vor Bad Hersfeld mit einem Kühlerschaden liegen. Schnell entschloss man sich die für die Wettkämpfe nötigen Geräte mit dem Bus zu holen. Um die Wettkämpfe durchzuführen lieh man sich ein weiteres LF8 der Gemündener Feuerwehr. Schließlich erreichte man mit 1171 Punkten den 11. Platz. Eine erfolgreiche Teilnahme der Leistungswettkämpfe in Korbach war 1978. In diesem Jahr konnte die Wehr zwei Mannschaften anmelden. Am Ende belegte Rennertehausen II mit 1197 Punkten den 5. Platz und Rennertehausen I mit 1222 Punkten den 3. Platz. Neben den Feuerwehr-Leistungswettkäpfen, nahm die Wehr regelmäßig an Pokalwettkämpfen bei befreundeten Wehren teil. Viele Urkunden und Pokale konnten hier gewonnen werden.</p>
        <p>Im Jahr 2018 gelang es der Feuerwehr Rennertehausen mit einer fehlerfreien &#220;bung und einer Knotenzeit von 25 Sekunden den 1. Platz beim Kreisentscheid in Korbach zu belegen.</p>
    </>
    );
}